### PR TITLE
Bump up versions of all ESlint dependencies

### PR DESCRIPTION
**Pull request by alexkilgour**
Making sure ESlint is fully up to date
https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes

Migration guidelines:
https://github.com/eslint/eslint/blob/master/docs/user-guide/migrating-to-5.0.0.md

### CODE REVIEW

**Comment by josebolos** [comment]
PR looks fine but this is something that will bump the minimum requirements of eslint to node 6.x or greater, which means that apps like shunter that are still supporting node 4.x won't be able to upgrade eslint for now.

Do you know what are the benefits of upgrading to eslint 5? Is this something we need to do now?

**Comment by alexkilgour** [comment]
There are quite a few bug fixes between the version we have and this version, plus quite a few new rules for newer features. I'm not sure it is essential to upgrade _now_, but do we think it is better to make these upgrades gradually? There is no reason shunter can use the previous version and newer projects can get support for newer features?

**Comment by jpw** [comment]
Good points, but I don't think we should hold fire on updates to this package based on needing to cater for older codebases.

**Comment by alexkilgour** [comment]
I agree with Jon, as I rather clumsily tried to say above 😆

**Pull request merged**
