### PR TITLE
Add more Yarn installation info

### PR DESCRIPTION
**Pull request by sonniesedge**
Add a quick addition based upon installing this package on a real Yarn environment.

### CODE REVIEW

**Comment by sonniesedge** [comment]
I'd advocate adding it as one of many _options_. We're already showing a `install-peerdeps` optoion in https://github.com/springernature/eslint-config-springernature/blame/master/README.md#L52

I agree that we shouldn't force a global install on users of the package, but showing an optional quick/automated installation method using a global package - that I can't see a fundamental problem with. 

I'll take a look and see if there's a npx-ish way of doing things with Yarn.

**Comment by sonniesedge** [comment]
Hmmm, interestingly, there's [no direct equivalent](https://github.com/yarnpkg/yarn/issues/3937) of `npx` in Yarn. The nearest is the [create](https://yarnpkg.com/lang/en/docs/cli/create/) command, which isn't that useful here I think.

**Comment by josebolos** [comment]
How about just using npx? From what I can get that npx does, I don't think that using yarn to install deps prevents us from using npx.

**Comment by sonniesedge** [comment]
Back from lunch. Hallo! I agree with that `npx` could be easily used in this case. 👍 I've updated the PR to reflect that. What do you think?

**Comment by sonniesedge** [comment]
Hurrah!

**Pull request merged**
